name: shared_libraries
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  async_redux: ^16.0.0
  camera: ^0.8.1+4
  carousel_slider: ^4.1.1
  debug_logger: ^0.0.23
  dartz: ^0.10.0-nullsafety.2
  dotted_border: ^2.0.0+2
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_image_compress: ^1.1.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  gql: ^0.13.0
  html: ^0.15.0
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^6.1.4
  local_auth: ^1.1.6
  material_design_icons_flutter: ^5.0.6996
  meta: ^1.3.0
  mocktail_image_network: ^0.3.1
  path: ^1.8.0
  path_provider: ^2.0.11
  pin_code_text_field: ^1.8.0
  photo_view: ^0.13.0
  platform: ^3.1.0
  rxdart: ^0.27.5
  shared_themes: ^0.2.0
  shimmer: ^2.0.0
  sms_autofill: ^2.2.0
  source_span: ^1.8.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.1.5
  visibility_detector: ^0.3.3
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  camera_platform_interface: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.5.3
  mockito: ^5.0.10
  test_api: ">=0.2.19"

flutter:
  uses-material-design: true
  assets:
    - packages/shared_libraries/ui_components/assets/ken.png
    - packages/shared_libraries/ui_components/assets/try_features.jpg
    - packages/shared_libraries/ui_components/assets/tza.png
    - packages/shared_libraries/ui_components/assets/uga.png
    - packages/shared_libraries/ui_components/assets/usa.png
    - packages/shared_libraries/ui_components/assets/ken.png
    - packages/shared_libraries/ui_components/assets/try_features.jpg
    - packages/shared_libraries/ui_components/assets/test-development.png
    - packages/shared_libraries/ui_components/assets/gbr.png
    - packages/shared_libraries/ui_components/assets/bel.png
    - packages/shared_libraries/ui_components/assets/nga.png
    - packages/shared_libraries/ui_components/assets/close.png
    - packages/shared_libraries/ui_components/assets/error.svg
    - packages/shared_libraries/ui_components/assets/info.svg
    - packages/shared_libraries/ui_components/assets/success.svg
    - packages/shared_libraries/user_feed/assets/hide.svg
    - packages/shared_libraries/user_feed/assets/pin.svg
    - packages/shared_libraries/user_feed/assets/resolve.svg
    - packages/shared_libraries/user_feed/assets/white_logo.png
    - packages/shared_libraries/user_feed/assets/white_logo.svg
    - packages/shared_libraries/user_feed/transparent_logo.svg
    - packages/shared_libraries/user_feed/assets/zero-state.png
    - packages/shared_libraries/user_feed/assets/swipe.png
    - packages/shared_libraries/user_feed/assets/cover_action.svg
    - lib/user_feed/assets/cover.png


